version: "3"
services:
  mysql56:
    build: ./mysql56
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql56/init:/docker-entrypoint-initdb.d/:ro
      - ./mysql56/data:/var/lib/mysql
  mysql57:
    build: ./mysql57
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=origin_operation_db
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql57/init:/docker-entrypoint-initdb.d/:ro
      - ./mysql57/data:/var/lib/mysql
  mysql8:
    build: ./mysql8
    ports:
      - "3302:3306"
    volumes:
      - ./mysql8/init:/docker-entrypoint-initdb.d/:ro
      - ./mysql8/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=origin_operation_db
      - MYSQL_ROOT_HOST=%
